spring:
  application:
    name : SpringBoot_SmartContactManager
  datasource:
    url : jdbc:mysql://localhost:3306/springboot_smart_contact_manager?createDatabaseIfNotExist=true
    username : root
    password : root
    driver-class-name : com.mysql.cj.jdbc.Driver

# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
    jpa:
      hibernate:
        ddl-auto : update
      show-sql : true

# spring.security.user.name= aazad
# spring.security.user.password= 1234

# oauth2 client configuration
# google configuration
  security:
    oauth2:
      client:
        registration:
          google:
           client-name : google
           client-id : 575184964404-m7vi0sa9vm8qhvb3rp8jff0d5e4kkalv.apps.googleusercontent.com
           client-secret : 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
           scope : email,profile

# github configuration
          github:
             client-name : github
             client-id : Iv23li1CPlmTy9vUMaHZ
             client-secret : f337bedee4bd93e4607eda695bdd3417cda0873d
             scope : email,profile

